name: Multi-Repo Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
      repositories:
        description: 'Repositories to process (comma-separated)'
        required: true
        default: 'asg-1,repo-2'
        type: string
  
  repository_dispatch:
    types: [terraform-trigger]

jobs:
  determine-repo:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - name: Set repositories to process
        id: set-repos
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "repos=['${{ github.event.client_payload.repository }}']" >> $GITHUB_OUTPUT
          else
            REPOS="${{ github.event.inputs.repositories }}"
            REPOS_JSON="[$(echo $REPOS | sed 's/,/","/g' | sed 's/^/"/;s/$/"/')]"
            echo "repos=$REPOS_JSON" >> $GITHUB_OUTPUT
          fi

  terraform:
    needs: determine-repo
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.determine-repo.outputs.repos) }}

    steps:
    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        echo "Processing repository: ${{ matrix.repo }}"

    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository_owner }}/${{ matrix.repo }}
        ref: ${{ github.event.client_payload.branch || 'main' }}
        token: ${{ secrets.PAT_TOKEN }}

    - name: Verify Directory Structure
      run: |
        echo "Contents of current directory:"
        ls -la
        echo "Contents of environments/prod (if exists):"
        ls -la environments/prod || echo "Directory not found"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    - name: Terraform Init
      working-directory: environments/prod
      run: terraform init

    - name: Terraform Validate
      working-directory: environments/prod
      run: terraform validate

    - name: Terraform Plan
      working-directory: environments/prod
      run: |
        terraform plan -out=tfplan
        
    - name: Terraform Apply
      if: |
        github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_action == 'apply' ||
        github.event_name == 'repository_dispatch' && github.event.client_payload.action == 'apply'
      working-directory: environments/prod
      run: terraform apply -auto-approve tfplan

    - name: Clean up
      working-directory: environments/prod
      run: rm -f tfplan
