name: Multi-Repo Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Terraform action to perform"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
      repositories:
        description: "Repositories to process (comma-separated)"
        required: true
        default: "asg-1,ec2"
        type: string
  repository_dispatch:  # ✅  
   types: [terraform-trigger]

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:  ${{ fromJson('["asg-1", "ec2"]') }}
    steps:
      - name: Remove Default Repo (`dope`)
        run: rm -rf ${{ github.workspace }}/*
      - name: Checkout Target Repository (${{ matrix.repo }})
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          ref: prod  # ✅ Checkout the correct branch
          path: ${{ matrix.repo }}  # ✅ Separate directories for each repo

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify Directory Structure  # ✅ Debugging Step
        run: ls -R ${{ matrix.repo }}
        
      - name: Terraform Init
        working-directory:  ${{ matrix.repo }}/enviroments/prod
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ matrix.repo }}/enviroments/prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.repo }}/enviroments/prod
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.terraform_action == 'apply'
        working-directory: ${{ matrix.repo }}/enviroments/prod
        run: terraform apply -auto-approve tfplan

      - name: Clean Up
        working-directory: ${{ matrix.repo }}/enviroments/prod
        run: rm -f tfplan
